server.document-root = "/git"
server.port = 80
server.modules = (
    "mod_cgi",
    "mod_alias",
    "mod_accesslog"
)

alias.url = ( "/zsmn-k8scd.git/" => "/git/zsmn-k8scd.git/" )

cgi.assign = (
    ".git" => ""
)

$HTTP["url"] =~ "^/zsmn-k8scd.git" {
    cgi.assign = ( "" => "" )
    setenv.add-environment = (
        "GIT_PROJECT_ROOT" => "/git",
        "GIT_HTTP_EXPORT_ALL" => "",
        "SCRIPT_FILENAME" => "/usr/lib/git-core/git-http-backend",
        "REMOTE_USER" => ""
    )
}

mimetype.assign = (
    ".json" => "application/json",
    ".yaml" => "text/yaml"
)