apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: temporal
data:
  POSTGRES_USER: temporal
  POSTGRES_DB: temporal
  POSTGRES_HOST: postgres.temporal.svc.cluster.local
  POSTGRES_PORT: "5432"
  VISIBILITY_DB: temporal_visibility