apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: temporal
type: Opaque
stringData:
  POSTGRES_USER: temporal
  POSTGRES_PASSWORD: temporal
  POSTGRES_DB: temporal
  DATABASE_TYPE: postgresql
  VISIBILITY_DB: temporal_visibility